{"uuid":"44dc6ed9-4eec-4c52-b876-37ef13bbca50","historyId":"f8c569e1b034a8ea9ec150bf27412c30","fullName":"page.PolicyPageTest.repettionAddDeclarePlanSuccess","labels":[{"name":"package","value":"page.PolicyPageTest"},{"name":"testClass","value":"page.PolicyPageTest"},{"name":"testMethod","value":"repettionAddDeclarePlanSuccess"},{"name":"parentSuite","value":"政沣云UI自动化测试"},{"name":"suite","value":"政策文库"},{"name":"subSuite","value":"page.PolicyPageTest"},{"name":"host","value":"LAPTOP-ISBERBL9"},{"name":"thread","value":"43364@LAPTOP-ISBERBL9.TestNG(27)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"政策文库"}],"links":[],"name":"repettionAddDeclarePlanSuccess","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [500] but found [401]","trace":"java.lang.AssertionError: expected [500] but found [401]\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:513)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:135)\r\n\tat org.testng.Assert.assertEquals(Assert.java:116)\r\n\tat org.testng.Assert.assertEquals(Assert.java:389)\r\n\tat org.testng.Assert.assertEquals(Assert.java:399)\r\n\tat page.PolicyPageTest.repettionAddDeclarePlanSuccess(PolicyPageTest.java:995)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\r\n\tat org.testng.TestRunner.run(TestRunner.java:610)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:39)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)\r\n\tat org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\n"},"stage":"finished","description":"异常测试用例：纳入已申报的计划失败","steps":[],"attachments":[],"parameters":[],"start":1718258743918,"stop":1718258744003}