{"uuid":"98ff3342-a0ad-4586-86ee-76cc7181dcf1","historyId":"c30a25a6a43a5415ebd7572a42a0e05e","fullName":"page.ClareStewardPageTest.fileEmptyAddSupportingMaterials","labels":[{"name":"package","value":"page.ClareStewardPageTest"},{"name":"testClass","value":"page.ClareStewardPageTest"},{"name":"testMethod","value":"fileEmptyAddSupportingMaterials"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ZhengFengYunApi"},{"name":"subSuite","value":"page.ClareStewardPageTest"},{"name":"host","value":"LAPTOP-ISBERBL9"},{"name":"thread","value":"20348@LAPTOP-ISBERBL9.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"政策文库"}],"links":[],"name":"fileEmptyAddSupportingMaterials","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [操作成功] but found [保存失败]","trace":"java.lang.AssertionError: expected [操作成功] but found [保存失败]\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:513)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:135)\r\n\tat org.testng.Assert.assertEquals(Assert.java:116)\r\n\tat org.testng.Assert.assertEquals(Assert.java:190)\r\n\tat org.testng.Assert.assertEquals(Assert.java:200)\r\n\tat page.ClareStewardPageTest.fileEmptyAddSupportingMaterials(ClareStewardPageTest.java:198)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\r\n\tat org.testng.TestRunner.run(TestRunner.java:610)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\r\n\tat org.testng.TestNG.run(TestNG.java:1104)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"异常测试用例：【佐证材料】文件为空，保存佐证材料失败","steps":[],"attachments":[],"parameters":[],"start":1718766693836,"stop":1718766708551}