{"uuid":"cba2f9bc-ad78-43c8-96eb-bfd23c007899","historyId":"674f2c0657f511a21b8f9dfcc0baa50d","fullName":"page.LoginPageTest.EmptyLoginFail","labels":[{"name":"package","value":"page.LoginPageTest"},{"name":"testClass","value":"page.LoginPageTest"},{"name":"testMethod","value":"EmptyLoginFail"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ZhengFengYunApi"},{"name":"subSuite","value":"page.LoginPageTest"},{"name":"host","value":"LAPTOP-ISBERBL9"},{"name":"thread","value":"6296@LAPTOP-ISBERBL9.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"登录"}],"links":[],"name":"EmptyLoginFail","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Expected to find an object with property ['password'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.","trace":"com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['password'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.\r\n\tat com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)\r\n\tat com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)\r\n\tat com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)\r\n\tat com.jayway.jsonpath.JsonPath.set(JsonPath.java:224)\r\n\tat com.jayway.jsonpath.internal.JsonContext.set(JsonContext.java:144)\r\n\tat conf.Api.lambda$updateApiFromMap$2(Api.java:66)\r\n\tat java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1126)\r\n\tat conf.Api.updateApiFromMap(Api.java:65)\r\n\tat conf.Api.getResponseFromYaml(Api.java:119)\r\n\tat page.LoginPage.passwordLoginSuccess(LoginPage.java:17)\r\n\tat page.LoginPageTest.EmptyLoginFail(LoginPageTest.java:135)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\r\n\tat org.testng.TestRunner.run(TestRunner.java:610)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\r\n\tat org.testng.TestNG.run(TestNG.java:1104)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"异常测试用例：验证码的key为空、错误，登录失败","steps":[],"attachments":[],"parameters":[],"start":1717407596551,"stop":1717407599712}